version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai3 --s3-location s3://kadai-kadai3/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src